### ISSUE TITLE
merge with ACE's bitmap_conv?

### ISSUE THREAD

**Issue by tehKaiN** [tditlu/amigeconv#1]
Hi there, I'm a main developer of [Amiga C Engine](https://github.com/AmigaPorts/ACE). My repo has also tool written in C + lodepng for converting bitmaps from png to custom, almost raw bitplane format.

Right now I'm during rewrite of said tool into C++ and I'm adding features like conversion in both directions. Perhaps we don't need to have two tools for same purpose, or even we could join forces in maintaining it?

Are there some specific features you need in such tool, namely some specific output file format?

**Comment by tditlu** [comment]
Didn't know about your project, maybe because your tool was "hidden" inside another project.
The project is mostly to ease my own cross developing demo programming, and I'm thinking of implementing everything useful that exists in the Amiga program: [PicCon](http://aminet.net/package/gfx/conv/PicCon250).

**Comment by tehKaiN** [comment]
So how about getting my tools outside of ACE into separate tools repo, to keep it unrelated and add support for various input toolchain formats? My tools are quite simple atm, but they support masked/non-masked, interleaved/classic bitmaps, palettes in different formats and fonts/tilemaps.

I'm not trying to press you into some sort of collaboration, but I think Amiga lacks proper modern coding-oriented toolset and I think having one polished suite is better than two similar, but smaller projects. ;)

**Comment by tditlu** [comment]
As i said before, this project is mostly to ease my own cross developing demo programming. I'm not interested in collaborating in making a universal tool, this will for now solve my needs for now so I can continue to work on my demo.
Thank you though for your interest in my project!

**Comment by tehKaiN** [comment]
fine, as you wish ;)
